### ISSUE TITLE
交流rknn

### ISSUE THREAD

**Issue by Daipuwei** [0zzx0/faster_deployment#1]

**Comment by Daipuwei** [comment]
我也在研究RKNN部署，请问你遇到过使用零拷贝后编译成功，但是运行后出现没有初始化零拷贝内存接口链接的bug吗
![20240423-150743](https://github.com/0zzx0/faster_deployment/assets/23739417/32443e59-6914-49ac-87e5-3d25af925aa9)

**Comment by Daipuwei** [comment]
如果可以能加为VX交流吗？我的微信：daipuwei-ai

**Comment by 0zzx0** [comment]
> 如果可以能加为VX交流吗？我的微信：daipuwei-ai

非常抱歉，暂时不方便VX。您这个板子和对应的版本我没有用过哎，我这边没有遇到这个情况。469385426是rknn官方的qq交流群，您可以在群里问一下。
